# Generated by Django 6.0.7 on 2026-07-09 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер зала', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text="Название зала (например, 'IMAX')", max_length=50)),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер ряда', validators=[django.core.validators.MinValueValidator(1)])),
                ('hall', models.ForeignKey(help_text='Зал', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cinema.hall')),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
                'ordering': ['hall', 'number'],
                'unique_together': {('hall', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название фильма', max_length=200)),
                ('started_at', models.DateTimeField(help_text='Время начала сеанса')),
                ('duration', models.IntegerField(help_text='Длительность в минутах', validators=[django.core.validators.MinValueValidator(1)])),
                ('hall', models.ForeignKey(help_text='Зал', on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='cinema.hall')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер места', validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(choices=[('standard', 'Стандартное'), ('vip', 'VIP')], default='standard', help_text='Тип места', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена билета', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('row', models.ForeignKey(help_text='Ряд', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.row')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['row', 'number'],
                'unique_together': {('row', 'number')},
            },
        ),
    ]
