# Generated by Django 6.0.7 on 2026-07-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(help_text='Название зала', max_length=50),
        ),
    ]
