# Generated by Django 6.0.7 on 2026-07-13 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_hall_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID пользователя (заглушка)')),
                ('status', models.CharField(choices=[('awaiting', 'Ожидает оплаты'), ('paid', 'Оплачена'), ('expired', 'Истекла')], default='awaiting', help_text='Статус брони', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания')),
                ('expires_at', models.DateTimeField(help_text='Время истечения брони')),
                ('seat', models.ForeignKey(help_text='Место', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.seat')),
                ('session', models.ForeignKey(help_text='Сеанс', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.session')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting', 'paid'])), fields=('session', 'seat'), name='unique_active_booking')],
            },
        ),
    ]
