# Generated by Django 6.0.7 on 2026-07-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='poster',
            field=models.URLField(blank=True, help_text='URL постера фильма', null=True),
        ),
    ]
